FROM node:16.20.0-slim

WORKDIR /app

# Copy API package files
COPY api/package.json ./
COPY docker/.env .

# Install API dependencies
RUN npm install --no-optional

# Copy API source code
COPY api/ ./

# Generate Prisma client
RUN npx prisma generate

# Build API
RUN npm run build

# Set environment variables
ENV NODE_ENV=production

# Expose port
EXPOSE 8080

# Start the application
CMD ["node", "dist/index.js"]
